wd_helper.au3

- Added: _WD_GetMouseElement
- Added: _WD_GetElementFromPoint

New functions

---

wd_core.au3

_WD_Alert fixes

---

wd_core.au3

I literally added "Gets, sets, or deletes the session's cookies", but something in here would be great :)

Add a description to _WD_Cookies

---

wd_core.au3
wd_helper.au3

~~(No code changes)~~
Added descriptions
Removed extra (empty) lines
Added _WD_Screenshot return values
N.B.: Diff for these changes doesn't appear to be working

Chore: Update function headers

---

wd_helper.au3

Added Return SetError to capture and re-throw error.
Updated function header to include all possible returned errors.

_WD_ElementOptionSelect - SetErrors

---

wd_core.au3

Call ProcessWaitClose after each attempt to close a process with ProcessClose

Change (__WD_CloseDriver): Call ProcessWaitClose

---

wd_helper.au3

parameters $sIndexOrID >> $vIdentifier
and descriptions extended

_WD_FrameEnter parameters description

---

wd_helper.au3

Fixed NULL usage and added Remarks

_WD_FrameEnter - fix for {"id":null}

---

wd_helper.au3

Remove unused $sJsonElement declaration

_WD_GetShadowRoot Au3Check Warning

---

wd_helper.au3

No need to set/save/restore the debug level to none inside this function ;)

Unnecessary Code

---

wd_helper.au3

Feature to wait till element not exist.

_WD_WaitElement + $_WD_OPTION_NoMatch

---

wd_core.au3

_WDCreateSession >_WD_CreateSession  
_WDFindElement > _WD_FindElement

wd_core.au3 - fixes for typos in FunctionNames used in function headers descriptions

---

wd_core.au3

_WD_GetSession($sSession) 	added #forceref $sSession, $sFuncName

---

README.md
wd_helper.au3

ps.
README.md is commited to this PR by mistake as this was comited into a patch I mean README.md was already in PR
https://github.com/Danp2/WebDriver/pull/76
commit:
https://github.com/Danp2/WebDriver/pull/76/commits/d5a87423d637f25af8ecfca720862a3d9d95f138
but there is no way to remove commit so can't PR 
`Local Const $sFuncName =`
without README.md changes.... 
EDIT:
I can only revert this README.md to keep clean this PR

_WD_UpdateDriver() move Local Const $sFuncName to first line

---

README.md
wd_helper.au3

These feature have been separated into separate functions to make it possible for the user to check it by themself.
```AutoIt
MsgBox(0, "", _WD_GetBrowserVersion('chrome') & @CRLF & _
"@error = " & @error & @CRLF & _
"@extended = " & @extended & @CRLF & _
"")
MsgBox(0, "", _WD_GetWebDriverVersion(@ScriptDir,'chromedriver.exe') & @CRLF & _
"@error = " & @error & @CRLF & _
"@extended = " & @extended & @CRLF & _
"")
```

wd_helper.au3 ++ _WD_GetBrowserVersion() ++ _WD_GetWebDriverVersion()

---

wd_helper.au3

Added COM Error handler to unzipping section: __WD_ErrHnd
Check for invalid or new $sInstallDir
Related to #70

_WD_UpdateDriver: Handle more errors

---

wd_core.au3

When I add "DefaultTimeout" I forget to suplement "Case Else"

_WD_Option - Case Else  + DefaultTimeout

---

wd_helper.au3

warning: $iErr possibly not declared/created yet

_WD_CheckContext - fix Au3Check warning

---

wd_core.au3

wd_core.au3 - Tidy code

---

wd_core.au3

​I was thinking about adding this `_WD_GetDevicePixelRatio()` to `wd_helper.au3` as there is similar `_WD_IsWindowTop()` which I usesd as an emplate for my _WD_GetDevicePixelRatio()
but...
Maybe we can add a new parameter $bReturnAsValue to `_WD_ExecuteScript`
​https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1493911

wd_core.au3 _WD_ExecuteScript() $bReturnAsValue

---

wd_helper.au3

Hi, I have added support for new `check` and `uncheck` commands in the `_WD_ElementActionEx` function. Please review the code and I'll amend it as appropriate for merge :)

Add check command in _WD_ElementActionEx

---

README.md
wd_helper.au3

_WD_GetElementFromPoint()  - refactoring

---

wd_core.au3
wd_helper.au3

In relation to:
https://github.com/Danp2/WebDriver/pull/115
and
https://github.com/Danp2/WebDriver/issues/116
Now it is less about 48 lines

wd_helper.au3 _WD_ExecuteScript() $vSubNode usage

---

wd_helper.au3

Cleaning Up _WD_Helper.au3 - part 2

---

wd_helper.au3

There is no scuch state as Success and Failure in this function.

_WD_LastHTTPResult - Return values

---

wd_helper.au3

https://github.com/Danp2/WebDriver/issues/141

_WD_UpdateDriver: Maintain $bForce value when Null

---

wd_demo.au3

btw.
I also notice that `_WD_Alert($sSession, 'sendtext', 'new text')` doesn't work.
Could you confirm this issue ?

Func DemoAlerts() - Refactoring

---

wd_helper.au3

WD_UpdateDriver() - $bFlag64 = Default handling

---

wd_demo.au3

Expand $aDemoSuite and revise code that launches demo functions

---

wd_demo.au3

For the clarity of the example for less experienced AutoIt programmers.

DemoActions() refactoring

---

wd_core.au3
wd_helper.au3

The discusion was started here:
https://www.autoitscript.com/forum/topic/191990-webdriver-udf-w3c-compliant-version-01192022/?do=findComment&comment=1494610

_WD_ElementSelectAction() - 'options' speed up

---

wd_helper.au3

- No longer calls _WD_HighlightElement in a loop
- Looping now handled in Javascript

_WD_HighlightElements refactoring

---

wd_demo.au3

_WD_JsonAction() was replaced for this case should be _WD_JsonActionPointer()
I will do some other changes, please wait.

DemoActions() fix

---

wd_helper.au3

related to:
https://github.com/Danp2/WebDriver/issues/168#issuecomment-1028365165
https://github.com/Danp2/WebDriver/issues/168#issuecomment-1028468810
https://github.com/Danp2/WebDriver/issues/168#issuecomment-1029773333

$sSelector - description

---

wd_demo.au3

[github.com/Danp2/au3WebDriver/issues/179](https://github.com/Danp2/au3WebDriver/issues/179)

wd_demo.au3 - refactoring : Headless & Update

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/PULL_REQUEST_TEMPLATE.md

Hi @Danp2 , hi @mlipok ,
this pull request provides additional files to fulfill recommended community standards. It's all about contribution and maintenance on GitHub. That's why GitHub recommend such files to regulate the community behavior and to ensure an effective way of contributing to the project(s).
Further explanation [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories) 😀 .
- bug_report.md and feature_request.md are suggested files for adding or opening an issue
- I adjusted the content just a little bit, the rest was generated by GitHub
- PULL_REQUEST_TEMPLATE.md helps to categorize
- I adjusted the content just a little bit, the rest was generated by GitHub
- CODE_OF_CONDUCT.md defines …

Added: Files to fulfill the community standards.

---

CHANGELOG.md
wd_helper.au3

Fix for: https://github.com/Danp2/au3WebDriver/issues/197

_WD_UpdateDriver() check _WD_DownloadFile() result

---

wd_core.au3

This is a begining.
@Danp2  please check if this will be aproved in this form.
Then I will check other functions

wd_core.au3 : __WD_Get() __WD_Post() __WD_Delete() - "URL" usage

---

wd_core.au3

`__WD_ConsoleWrite()` should support to write the log to user specified output
`__WD_ConsoleWrite` can only log to console output or to file but why only this two options ?
`__WD_ConsoleWrite` can log to user specified function
none.
not related

__WD_ConsoleWrite support for log to own function

---

wd_capabilities.au3

Trynig to follow this request
https://github.com/Danp2/au3WebDriver/pull/208#discussion_r810485788
`_WD_Capabilities doesn't honor the new output target`
using `ConsoleWrite`
using `__WD_ConsoleWrite`
None
Not related

wd_capabilities.au3 using __WD_ConsoleWrite

---

wd_demo.au3

Added demo for _WD_Option('console','***') into wd_demo.au3 
wd_demo.au3 does not include example for  _WD_Option('console','***')
added example for  _WD_Option('console','***') to wd_demo.au3 
none
not related

wd_demo.au3 + _WD_Option('console','***')

---

wd_core.au3
wd_helper.au3

fix for:  [$oNameSpace.items The requested action with this object has failed](https://github.com/Danp2/au3WebDriver/issues/203)
https://github.com/Danp2/au3WebDriver/issues/203
works without errors
https://github.com/Danp2/au3WebDriver/issues/203
not related

_WD_UpdateDriver fix for $oNameSpace.items

---

wd_demo.au3

I make this PR to test how to commit to...
not all browsers are supported in the demo
Pre added support for Opera browser
None
not related

wd_demo.au3 Opera first commit

---

wd_capabilities.au3

added support for 'operaOptions'
lack of support for  'operaOptions'
added support for  'operaOptions'
https://github.com/Danp2/au3WebDriver/issues/187
OPERA

__WD_CapabilitiesInitialize + 'operaOptions'

---

README.md

Update ReadMe to include Opera support

Readme update for opera

---

wd_core.au3

related to @Danp2  findings:
https://github.com/Danp2/au3WebDriver/issues/220#issuecomment-1050344696
capabilities for opera are **not** properly build.
capabilities for opera are properly build.
https://github.com/Danp2/au3WebDriver/issues/220#issuecomment-1050344696
OPERA browser

wd_core.au3 - operaOptions > goog:chromeOptions

---

wd_helper.au3

This PR is a fix for the issue catched by : [n3wbie](https://www.autoitscript.com/forum/profile/93584-n3wbie/) AutoIt forum member, and [reported here](https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1496813).
If `$sInstallDir` contains incorrect path for example `/` was used instead `\` then _WD_UpdateDriver() function breaks the scripts on:
```autoit
"Z:\!!!_SVN_AU3\UDF_Forum\Other_Members\Official_AutoIt_Forum\WebDriver\wd_helper.au3" (1433) : ==> The requested action with …
```

_WD_UpdateDriver - better error handling

---

wd_core.au3
wd_helper.au3

Eliminate remaining hardcoding in _WD_UpdateDriver. 
_WD_UpdateDriver contains hardcoding for each browser
Elimination of hardcoding by expanding $_WD_SupportedBrowsers and adding __WD_GetLatestWebdriverInfo

_WD_UpdateDriver: Eliminate remaining hardcoding

---

wd_core.au3
wd_demo.au3

cleanup comments etc......
Hope all is ok
Finall review
none
NOT RELATED

Opera final proposals

---

CHANGELOG.md
README.md
wd_capabilities.au3
wd_core.au3
wd_demo.au3
wd_helper.au3

Add support for Opera browser

---

CHANGELOG.md
wd_core.au3

There was an error in checking bitness.
This is fix for this following issue:
https://github.com/Danp2/au3WebDriver/issues/240
Incorrect driver bitness checking in `_WD_Startup()`
Correct driver bitness checking in `_WD_Startup()`
https://github.com/Danp2/au3WebDriver/issues/240
Not related

_WD_Startup - fixed bitness checking

---

CHANGELOG.md
wd_capabilities.au3
wd_cdp.au3
wd_core.au3
wd_helper.au3

There is not needed in all __WD_ConsoleWrite line to add `@CRLF  ` 
It should be moved to to internall processing into `__WD_ConsoleWrite()`  function.
A the same time:
`__WD_ConsoleWrite` should support for other suffixes not olny `@CRLF`
For example If I use:
```autoit
_WD_Option("console", _Log_To_DataBase)
```
Then there is no need to write `@CRLF` to data base which stores log entries in separate database rows.
So using
```autoit
_WD_Option("consolesuffix", "")
_WD_Option("console", _Log_To_DataBase)
```
will fit this needs.
This is also code refactoring as now we ara not using `@CRLF` all the time when `__WD_ConsoleWrite()` is used.
This is simply a reminder of …

$_WD_CONSOLE_Sufix moved @CRLF to internall scope

---

wd_core.au3
wd_demo.au3

It makes easier to use wd_demo.au3 for checking if UDF works fine after each new changes, when messages from wd_demo.au3 differ form messages form UDF
Uncoherent messages in console
Coherent console messages, easier testing.
Removed magic number and added `$MB_TOPMOST`
Also fixed `_WD_Startup()` in relation to `If $_WD_DEBUG = $_WD_DEBUG_Info Then`
it is continuation for https://github.com/Danp2/au3WebDriver/pull/252
Not Releated

demo: Refactoring

---

wd_helper.au3

`$iExt` was not returned properly out of `_WD_UpdateDriver()`
`$iExt` is returned properly out of `_WD_UpdateDriver()`
None
Not related

_WD_UpdateDriver - $iExt fixed

---

wd_core.au3
wd_helper.au3

Misc cleanup

---

wd_core.au3

There is message put into console even when `$_WD_DEBUG_None` is set
Full info is put into console only when `$_WD_DEBUG_Info` is set
There is no message put into console even when `$_WD_DEBUG_None` is set.
Full info is put into console when `$_WD_DEBUG_Info`  is set but also when error occured and `$_WD_DEBUG_Error` is set.
None
Not related

Func _WD_Startup() refactoring

---

wd_core.au3

_WD_Cookies: Fix deletion

---

wd_core.au3

Add ability for end user to retrieve UDF version using _WD_Option.

Support _WD_Options('version')

---

wd_demo.au3

`http://` >> `https://` should be used

http > https

---

wd_core.au3

$_WD_OHTTP is declared but no used
$_WD_OHTTP is removed
None
Not related

$_WD_OHTTP removed as unsued

---

wd_helper.au3

wrong `$sFuncName = "__WD_GetLatestWebdriverURL"`
proper `$sFuncName = "__WD_GetLatestWebdriverInfo"`
None
Not related

$sFuncName = "__WD_GetLatestWebdriverInfo"

---

wd_core.au3

There is no truly debug level of debuging.
using `$_WD_DEBUG_Full` you can do this:
```auotit
__WD_ConsoleWrite($sFuncName, 'some test #' & @ScriptLineNumber, $_WD_DEBUG_Full)
```
```autoit
#include "wd_core.au3"
_Test()
Func _Test()
Local Const $sFuncName = '_Test'
$_WD_DEBUG = $_WD_DEBUG_None
ConsoleWrite('! ' & @CRLF)
__WD_ConsoleWrite($_WD_DEBUG & '> test Default #' & @ScriptLineNumber)
__WD_ConsoleWrite($_WD_DEBUG & '> test None #' & @ScriptLineNumber, $_WD_DEBUG_None)
__WD_ConsoleWrite($_WD_DEBUG & '> test Error #' & …
```

$_WD_DEBUG_Full support

---

wd_helper.au3

`$bEXEWasFound` is not set if EXE is lotacted in subfolder
`$bEXEWasFound` is set properly
none
not related

__WD_UpdateExtractor error handling

---

wd_demo.au3

lack of support for `$_WD_DEBUG_Full`
added support for `$_WD_DEBUG_Full`
none
not related

Demo: $_WD_DEBUG_Full support

---

wd_core.au3

```autoit
;                  Failure - None
```
it never happens.
fixed
added remarks
not related

__WD_Error - function header

---

wd_capabilities.au3
wd_core.au3

`_WD_CapabilitiesDisplay` - removed as not needed anymore
`$_WD_CAPS__API` and `_WD_CapabilitiesDisplay` was used because I was not so familiar with 
https://w3c.github.io/webdriver/#capabilities
and with
https://www.autoitscript.com/forum/topic/148114-a-non-strict-json-udf-jsmn
There is no need of `$_WD_CAPS__API` and `_WD_CapabilitiesDisplay` all is …

$_WD_CAPS__API and _WD_CapabilitiesDisplay - removed

---

wd_core.au3

Added: _WD_LastHTTPResponse

---

wd_demo.au3

User may not be able to click on the confirmation message, I mean not able to click before script goes further.
Check if first DIV element is visible, as it can hide all sub elements in case when COOKIE aproval message is visible
Script waits and shows error on TimeOut
https://github.com/Danp2/au3WebDriver/pull/292#discussion_r848846752
NOT RELATED

wd_demo: COOKIE aproval message

---

wd_demo.au3

1. `https://demo.guru99.com/` wrong URL was used.
2. not well documented `DemoScript()` example 
1. fixed URL
2. better `DemoScript()` example 
https://github.com/Danp2/au3WebDriver/issues/254#issuecomment-1104475735
not related

wd_demo.au3 - DemoScript() examples + descriptions

---

wd_helper.au3

Premature exit of loop
Continue processing if folder didn't contain desired file

Only exit loop if folder contained executable

---

wd_core.au3
wd_helper.au3

Addition of a new function called `_WD_FindElement_ByRegExp` to match elements with regular expressions.
N/A - Generic - Universal - Agnostic

Add _WD_GetElementByRegEx

---

wd_core.au3

Enhance __WD_DetectError to identify Javascript related errors
Javascript related errors go undetected and fall into the generic category of `$_WD_ERROR_Exception`
When a Javascript error is detected, the new `$_WD_ERROR_Javascript` error code will be used unless a more specific error code is identified
`__WD_DetectError` is called by `__WD_Get`, `__WD_Post`, and `__WD_Delete`. Therefore, this change could affect most of the existing UDFs
N/A

Detect Javascript errors

---

wd_demo.au3

I notice that there is a need to easilly share testing code snippet.
For example:
https://github.com/Danp2/au3WebDriver/issues/314
https://github.com/Danp2/au3WebDriver/issues/308#issuecomment-1139054806
wd_demo.au3 have only pre defined functions, user do not have possibility to easilly check his own stuff
added `UserTesting()`  for testing user stuff, also for testing BUG reports.
https://github.com/Danp2/au3WebDriver/issues/314
https://github.com/Danp2/au3WebDriver/issues/308#issuecomment-1139054806
not related

adding UserTesting() to wd_demo.au3

---

README.md
wd_helper.au3

Adding support for set/get style property
there is no helper function to set/get style property
added `_WD_ElementStyle()`
https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1501634
not related

Add: _WD_ElementStyle

---

wd_demo.au3

added example for multiple selection
no demo for select multile options
addded DemoSelectOptions()
https://github.com/Danp2/au3WebDriver/issues/177

wd_demo.au3 - addded DemoSelectOptions() + DemoStyles()

---

CHANGELOG.md
wd_cdp.au3

Correct variable name in _WD_CDPExecuteCommand
Missing $ prefix
Correct variable name

Correct variable name in _WD_CDPExecuteCommand

---

CHANGELOG.md
wd_core.au3
wd_demo.au3
wd_helper.au3

Update _WD_ElementSelectAction to check `hidden` attribute
Function fails to check the `hidden` attribute, so it could try to select an invalid option element
1) Perform additional checks to ensure `option` element isn't hidden
2) Return hidden status as additional column in array
#345 
#

_WD_ElementSelectAction: Check hidden status

---

CHANGELOG.md
wd_core.au3

Update documentation (readme and changelog) in preparation for next release
N/A

Prep Release

---

wd_helper.au3

refactoring JS for better code maintaince.
hard to move and test in browser Console
easier JS code maintaince
none
not related

_WD_ElementSelectAction 'selectedLabels' JS refact

---

wd_helper.au3

Case Insensivity as requested here: https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1218443860
Code is refactored to use the same JS variable names, and the same JS coding style
if you use
```autoit
_WD_ElementSelectAction($sSession, $sSelectElement, 'SINGLESELECT', 'ParroT')
```
instead
```autoit
_WD_ElementSelectAction($sSession, $sSelectElement, 'SINGLESELECT', 'Parrot')
```
then you will get error= `$_WD_ERROR_NoMatch`
no error, element is selected
https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1218443860
not related

_ElementSelectAction : JS refactoring + case insensivity

---

wd_demo.au3
wd_helper.au3

discussion was taken here: https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1220869303
https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1220869303
https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1220869303
https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1220869303
not related

_WD_ElementSelectAction almost finall review

---

wd_helper.au3

Add option that allows _WD_WaitElement to check the visibility of an element and return when it is no longer visible.
Checks exist for visible and enabled, but not hidden
Add ability to check for hidden element

_WD_WaitElement: Allow check for hidden element

---

wd_helper.au3

Update code to remove browser specific checks
Original coding processed response differently between Chrome & Firefox
Simplified coding by removing browser specific checks

Refactor _WD_FrameLeave

---

wd_core.au3
wd_helper.au3

Standardization of descriptions and variable names
See #398

Standardization of descriptions and variable names

---

wd_core.au3
wd_helper.au3

Add function _WD_GetFreePort
No easy means to identify an alternate port number that is available for use
_WD_GetFreePort can be called to obtain a free port number within a defined range

Add _WD_GetFreePort

---

wd_core.au3

Remove unneeded variable to avoid error from AU3Check
_WD_Startup() throws error from AU3Check
Avoid error from AU3Check
Fixes #408 

Remove unneeded variable

---

wd_core.au3
wd_helper.au3

- Add new error code to indicate an invalid browser context
- Improve _WD_CheckContext and _WD_CheckContext error detection / handling to include invalid browser context
No detection of invalid browser context
Functions are enhanced to detect / handle when an error related to invalid browser context occurs

Invalid browser context improvements

---

wd_demo.au3

fixing issue [_WD_CreateSession and WD_Demo extension ](https://github.com/Danp2/au3WebDriver/issues/424)
https://github.com/Danp2/au3WebDriver/issues/424
Fixed.
https://github.com/Danp2/au3WebDriver/issues/424
Firefox

wd_demo.au3 - SetupGecko - preset browser location

---

wd_core.au3

_WD_CreateSession - better error handling
not detailed enough error logs in some cases
better error handling
https://github.com/Danp2/au3WebDriver/issues/424#issuecomment-1446089795
not related

_WD_CreateSession - better error handling

---

wd_core.au3

Improve messages returned in _WD_ExecuteScript
Generic message `Error occurred when trying to ExecuteScript` is logged
Utilize message returned by webdriver instead of generic message

_WD_ExecuteScript: Custom messages

---

wd_helper.au3

Add a new function that takes JavaScript code and waits until the code returns true
New function
New function
- Browser [e.g. chrome]
- Browser version [e.g. 110.0]

Add _WD_WaitScript function

---

CHANGELOG.md
wd_helper.au3

not only <iframe> but also <frame> should be checked
script check if result of `document.elementFromPoint(arguments[0], arguments[1])` is NOT   <iframe>  but not checks for <frame>
script check if result of `document.elementFromPoint(arguments[0], arguments[1])` is NOT   <iframe>  but also <frame>
https://github.com/Danp2/au3WebDriver/issues/369#issuecomment-1487250656
not related

_WD_GetElementFromPoint <frame> support

---

CHANGELOG.md
wd_cdp.au3
wd_core.au3
wd_demo.au3
wd_helper.au3

Support new release process for Chromedriver
See #473 
- New download location for chromedriver
- Enable 64 bit support

Update chromedriver support

---

CHANGELOG.md
README.md
wd_cdp.au3
wd_helper.au3

Enhance _WD_GetTable to support overriding of default table markers
Table markers are fixed.
- Customizable table markers
- Drastically improved speed

_WD_GetTable: Support non-standard tables and improve speed

---

wd_capabilities.au3
wd_cdp.au3
wd_core.au3
wd_demo.au3
wd_helper.au3

This PR adds better TIDY support
TIDY behavior can differ by user IDE settings, thus using TIDY between developers can produce different results.
Pre declared TIDY behavior protects against unnecessary problems with the use of TIDY by different developers
none
not related

better TIDY support

---

wd_helper.au3

Added remark about nested tables.
not related
not changed
none
https://github.com/Danp2/au3WebDriver/issues/496
not related

_WD_GetTable() - function header changes related to nested table

---

wd_core.au3

Please see Issue #514 . I described all there. Thanks.
Please see Issue #514 .
Please see Issue #514 .
Please see Issue #514 .
Please see Issue #514 .
I tested the change on Chrome, Firefox and MSEdge.

Changed: Extend '_WD_Window' function by restore option.

---

wd_core.au3

This PR should fix the issue #523.
I hope this is simply enough, otherwise I am sure you @Danp2 will let me know what's missing 😅 .
Best regards
Sven

Documented: Fix the verbiage of URL option in '_WD_Action' function.
