Danp2/au3WebDriver

wd_helper.au3

Hi, I have added a new `_WD_ExecuteCdpCommand` function in `wd_helper.au3`, it should be useful for those who are looking to use the advanced capabilities of the Chrome DevTools Protocol via ChromeDriver :smile:

Added: _WD_ExecuteCdpCommand

---

wd_core.au3

This two following include files
```
#include <JSON.au3>
#include <WinHttp.au3>
```
are not Standard AutoIt UDF so should be used "" instead <>
```
#include "JSON.au3"
#include "WinHttp.au3"
```
according to helpfile
https://www.autoitscript.com/autoit3/files/beta/autoit/docs/keywords/include.htm
```
If "..." is used, the filename is taken to be relative to the current script.
If <...> is used the filename is taken to be relative to include library directory (usually C:\Program Files\AutoIt3\Include). The include library contains many pre-written user-functions for you to use!
```

#include "" instead #include <>

---

wd_helper.au3

There was:
Local Const $sFuncName = "_WD_SelectUploadFile"
Such function currently not exist.

Local Const $sFuncName = "_WD_SelectFiles"

---

wd_helper.au3

In  _WD_ElementActionEx() header in Parameters Description there was lack of "clickandhold"

_WD_ElementActionEx - "clickandhold" description

---

wd_core.au3

User should be able to adjust this default value.
I can imagine that someone has a very poor connection and is doing a project, e.g. got a freelancer contract, and now has to adjust to a slower connection.

wd_core.au3 - $_WD_DefaultTimeout - not as Const

---

wd_demo.au3

After demo runs and ends processing, they should'nt close GUI" `GUICreate("Webdriver Demo"...`
As I said:
https://github.com/Danp2/WebDriver/pull/97#issuecomment-981617708
now it is easier to continue.

wd_demo.au3 - added RunDemo()

---

wd_helper.au3

Please also take a look on 
`Func __WD_Base64Decode($input_string)`
as the description:
`; Return values .: Decoded string`
doesn't conatin information about Success/Failure/@error

_WD_Screenshot - better @error handling

---

wd_helper.au3

https://github.com/Danp2/WebDriver/pull/139#issuecomment-1021198135
If `$bFlag64 = Default` then update should perform checking which version is used.

_WD_UpdateDriver() - $bFlag64 = Default handling

---

wd_demo.au3

better DemoCookies()
something went wrong with merging my last 2x COOKIES  PR's
This is how I have this demo stored on my disc when I was working on: 
https://github.com/Danp2/au3WebDriver/pull/194
and
https://github.com/Danp2/au3WebDriver/pull/195
There was lack of 
```AutoIt
#include <Date.au3>
```
not related.

DemoCookies() refactoring

---

wd_core.au3

`__WD_ConsoleWrite()` should support an easy way to disable any write to any output.
Currently you can only use feature which sends data to some kind of output.
```autoit
Func __WD_ConsoleWrite($sMsg)
If $_WD_CONSOLE = Default Then
ConsoleWrite($sMsg)
ElseIf IsFunc($_WD_CONSOLE) Then
Call($_WD_CONSOLE, $sMsg)
Else
FileWrite($_WD_CONSOLE, $sMsg)
EndIf
EndFunc   ;==>__WD_ConsoleWrite
```
You can easilly set NULL as output device
```AutoIt
ElseIf $_WD_CONSOLE = Null Then
; do nothing
```
by using:
```autoit
_WD_Option('console', Null) …
```

__WD_ConsoleWrite() NULL/Disable support

---

wd_helper.au3

https://www.autoitscript.com/forum/topic/205553-webdriver-udf-help-support-iii/?do=findComment&comment=1497208
On some Windows installations, the WebDriver EXE file does not unpack.
Unpack EXE in such cases. …

_WD_UpdateDriver - fix for unpacking ".exe" file

---

wd_core.au3

UDF Maintainers and UDF users should have better/easier way to debug script.
Shows only driver name in console at `_WD_Startup()` usage.
Check and shows also DriverBitness in console at `_WD_Startup()` usage.
Today @Danp2  [ask me about operadriver.exe bitnes](https://github.com/Danp2/au3WebDriver/pull/218#discussion_r814750839).
I had to check it somehow, so I change the script.
Thus my PR.
not related

_WD_Startup: $sDriverBitness information

---

wd_helper.au3

Support alternate browser location in _WD_UpdateDriver
https://github.com/Danp2/au3WebDriver/issues/187#issuecomment-1051339319
Unable to update webdriver for portable / alt versions of browser
_WD_UpdateDriver now accepts the full path of the browser executable for $sBrowser parameter
None
N/A

Support alternative browser locations in _WD_UpdateDriver

---

wd_core.au3
wd_helper.au3

I have added more error handling and fixed `_WD_UpdateDriver` in case when file full path is used `Extract filename from full path`
```AutoIt
If $iErr = $_WD_ERROR_Success Then
If StringInStr($sBrowser, '\') Then
; Extract filename from full path
$sBrowser = StringRegExpReplace($sBrowser, "^.*\\|\..*$", "")
EndIf
; Match in list of supported browsers
Local $iIndex = _ArraySearch($_WD_SupportedBrowsers, $sBrowser, Default, Default, Default, Default, Default, $_WD_BROWSER_Name)
$sDriverEXE = $_WD_SupportedBrowsers[$iIndex][$_WD_BROWSER_DriverName]
```
Please check `x` the type of change …

OPERA:  _WD_GetBrowserVersion/Path refactoring

---

wd_helper.au3

Support for unpacking opera driver which is placed in subfolder in zip archive
it is not able to unpack opera driver
support for unpacking exe file from subfolder
https://github.com/Danp2/au3WebDriver/issues/187
NOT RELATED

OPERA: _WD_UpdateDriver + __WD_UpdateExtractor

---

wd_capabilities.au3

When user pass wrong browser name which was reported in:  [__WD_CapabilitiesInitialize: Needs to validate result of _ArraySearch](https://github.com/Danp2/au3WebDriver/issues/250)
or initialization was not performed at first place functions 
.... then function should return error and not set capabilites JSON string.
Take a look here: [__WD_CapabilitiesInitialize: Needs to validate result of _ArraySearch](https://github.com/Danp2/au3WebDriver/issues/250)
Fixed. Function returns error and not setting any capabilities JSON string. …

wd_capabilites: validate result of Initialization

---

wd_demo.au3

Setting Debug to none should shown less info in console.
I notice that each console with "none" should comes only from demo and should differ from messages from UDF.
Thus I added "> " to consolewrite
demo console messages **it does not** differ from UDF messages.
demo console messages differ from UDF messages.
It makes easier to use wd_demo.au3 for checking if UDF works fine after each new changes, when messages from wd_demo.au3 differ form messages form UDF
NOT RELATED

demo: Refactoring

---

wd_capabilities.au3

$_WD_DEBUG it should be considered specifically when it is = $_WD_DEBUG_None
messages are sent to console even when $_WD_DEBUG = $_WD_DEBUG_None
$_WD_DEBUG = $_WD_DEBUG_None is checked
not related

_WD_CapabilitiesDump relates on $_WD_DEBUG

---

wd_helper.au3

after `If FileExists($sBrowser) Then` 
`$sBrowser` cant be changed from `FileFullPath` to `FileName`  because in next few lines `$sPath = $sBrowser` and then this following part
```autoit
If _WinAPI_GetBinaryType($sPath) = 0 Then ; check if file is executable
$iErr = $_WD_ERROR_FileIssue
$iExt = 31
Else
```
set Error and Extended, and this is all because `FielFullPath` is changed to `FileName`
`$sBrowser` is not changed and `_WinAPI_GetBinaryType($sPath)` returns proper results
None
Not related

_WD_GetBrowserVersion() fixing check BinaryType

---

wd_capabilities.au3

Old way to use `"--profile-directory"` (Keyword `Default`):
```autoit
_WD_CapabilitiesAdd("args", "--profile-directory", Default)
```
New proper way to use `"--profile-directory"`  (string `"Default"`):
```autoit
_WD_CapabilitiesAdd("args", "--profile-directory", 'Default')
```
not common usage
`$value1 = '', $value2 = ''`
common usage
`$value1 = …

_WD_CapabilitiesAdd() Default parameters value

---

wd_demo.au3

**wd_demo.au3** messages in console were distinguishable from **wd_core.au3** and **wd_helper.au3** only by color
currently **wd_demo.au3** messages in console are prefixed with `wd_demo.au3: `
This helps to distinguish demo messages from UDF messages
- OS: [e.g. …

wd_demo: improved messages in console

---

wd_demo.au3
wd_helper.au3

Was not able to set `$sElementSelector` value in case when Cookie Aproval message was visible
waiting on user aprove Cookie request
https://github.com/Danp2/au3WebDriver/issues/254#issuecomment-1096874196
not related

WD_WaitElement() Fix for $bCheckNoMatch usage

---

wd_helper.au3

`$_WD_HTTPRESPONSE` is not always cleared
`$_WD_HTTPRESPONSE = ''` must be reset as well as `$_WD_HTTPRESULT = 0`
https://github.com/Danp2/au3WebDriver/pull/295#issuecomment-1101715311
Not Related

$_WD_HTTPRESPONSE cleared as $_WD_HTTPRESULT

---

wd_core.au3

Displays incorrect bit level when driver is set to non-executable file
No bit level displayed when _WinAPI_GetBinaryType fails

_WD_Startup: Check _WinAPI_GetBinaryType result

---

wd_core.au3

Update _WD_ElementAction to correctly support ComputedLabel and ComputedRole commands
Wrong commands in _WD_ElementAction 
Update coding to support the correct webdriver commands --
compdlabel ==> computedlabel
comprole ==> computedrole

Fix: _WD_ElementAction supported commands

---

wd_demo.au3

Use standard GUI buttons instead of checkboxes with $BS_PUSHLIKE
See #311 
Using standard buttons allows for updating the control's background color when needed
None
- OS: Windows 11

Use standard buttons instead of checkboxes

---

wd_core.au3

_WD_Startup should show PID in log when existing instance of webdriver is detected
no information about PID of existing instance
PID of existing instance is loged
none
not related

_WD_Startup - logging the PID of an existing instance

---

wd_demo.au3

this examples are related to: 
[_WD_ElementSelectAction + checking if disabled](https://github.com/Danp2/au3WebDriver/pull/330)
DemoSelectOptions - was not showing how _WD_ElementSelectAction() acts when <Option> element or <OPTGROUP> was disabled
DemoSelectOptions is extended to show case when elements are disabled.
[_WD_ElementSelectAction + checking if disabled](https://github.com/Danp2/au3WebDriver/pull/330)
not related

DemoSelectOptions - examples with disabled groups

---

wd_helper.au3

Better `$_WD_OPTION_Advanced` implementation in `_WD_SetElementValue`
`_WD_SetElementValue` with `$_WD_OPTION_Advanced` still not always properly sets value.
`$_WD_OPTION_Advanced` fires `change` event for this reason all background processing are processed. 
None
not related.
But mostly issue with setting value occurs on Firefox in case when Firefox was visible but was obscured by another window.

_WD_SetElementValue $_WD_OPTION_Advanced usage

---

CHANGELOG.md
wd_helper.au3

Add _WD_Storage function to allow manipulation of localStorage and sessionStorage
No simple way to access browser storage
UDF to control access to browser storage
Tested with variations of this code --
```autoit
Func UserTesting() ; here you can replace the code to test your stuff before you ask on the forum
_WD_Navigate($sSession, 'https://www.google.com')
_WD_LoadWait($sSession)
$sResult = _WD_Storage($sSession, 'testing', '123')
;### Debug CONSOLE ↓↓↓
ConsoleWrite('@@ Debug(' & @ScriptLineNumber & ') : $sResult = ' & …
```

Add ability to control browser storage

---

CHANGELOG.md
wd_capabilities.au3

- Wrap keys in double quotes to avoid truncation 
- Add `webSocketUrl` to $_WD_KEYS__STANDARD_PRIMITIVE
When `$s_Notation = [capabilities][alwaysMatch][moz:debuggerAddress]`, the portion following the colon gets truncated
```
_WD_CapabilitiesAdd: #177 :      $key = moz:debuggerAddress     $value1 = True     $value2 = 
_WD_CapabilitiesAdd: #217 #273 :      $key = moz:debuggerAddress     $value1 = True     $value2 =     $s_Notation = [capabilities][alwaysMatch][moz:debuggerAddress]   <<<<  True
_WD_CapabilitiesAdd ==> Success [0] : …
```

Update _WD_Capabilities 

---

CHANGELOG.md
wd_helper.au3

In some cases selecting options should fire Change and Bubbles events.
_WD_ElementSelectAction not always properly select Options because DOM structure was not interacting with the change.
_WD_ElementSelectAction fires event to for DOM structure to notice the change.
https://github.com/Danp2/au3WebDriver/issues/344
not related

_WD_ElementSelectAction: Selecting options +Events

---

wd_demo.au3

I made FR here: https://github.com/Danp2/au3WebDriver/issues/354
And I realizie that I had to add new Function() that are subject to review.
The same situation may arise if someone wants to report a problem.
That's why I found the whole region useful for testing and additional commentary.
In addition, I found that just in case it would be good to add validation if the session is correct, as basically the whole demo does not use it, and in the case of `UserTesting` scripts it would be helpful.
no session validation
no additionall space where user should put speciall testing function
added session validtation
```autoit
_WD_CheckContext($sSession, False)
If @error Then ; return if session is NOT OK
ConsoleWrite("! ---> @error=" & @error …
```

UserTesting() session validation and extra space

---

README.md

Adds details for integrating the UDF into an AutoIt Github Repo as a submodule for easy dependency updates.
The UDF must be downloaded from releases and uploaded to a project using it. Afterwards, this process must be manually completed for any updates.
The UDF can now be "embedded" within another repo and updated using `git submodule update`. Allowing for better CI, dependency, and overall AutoIt Github project handling.
As AutoIt does not include any way to manage and update dependencies for projects automatically, git submodules …

Add details for using UDF as submodule

---

wd_demo.au3

NID cookie may not exist at start, may appear later when website will be estabilished, so there is need to wait on @error and try again
`NID` may not exist after even after `_WD_LoadWait`  
DemoCookies() waits on NID cookie existence
[wd_demo: review all "Demo****" function](https://github.com/Danp2/au3WebDriver/issues/254)
not related

DemoCookies() waits on NID cookie existence

---

wd_core.au3

If function check the status and it is obvious that on false there should be Error , and in this particular case as this is obvious and expected behavior of checking `status` it should not be reported to user as error.
```
+ wd_demo.au3: Running: DemoAlerts
__WD_Get ==> No alert present [12] : HTTP status = 404
_WD_Alert ==> No alert present [12] : Parameters:   Command=status   Option=Default
wd_demo.au3: (522) : Alert Detected => False
```
```
+ wd_demo.au3: Running: DemoAlerts
__WD_Get ==> No alert present [12] : HTTP status = 404
wd_demo.au3: (522) : Alert Detected => False
```
was discussed here:
https://github.com/Danp2/au3WebDriver/pull/371#discussion_r940182350
not related

_WD_Alert 'status' return success on False

---

wd_demo.au3

this PR is only related to the comment that describe in the specific case what kind of expected result should be to check Alert status
`; check status before displaying Alert`
`; check status before displaying Alert - this should set @error as there is no any Alert displayed yet`
I was checking examples for this ISSUE #254 
not related

DemoAlerts() - show that prompt was set

---

wd_helper.au3

This PR add support for:
```autoit
_WD_FrameEnter($sSession, 'null/2/0')
```
no way to provide relative/abolute path to desired frame at once
```autoit
_WD_FrameEnter($sSession, 'null/2/0')
```
https://github.com/Danp2/au3WebDriver/pull/363
and as I said here:
https://github.com/Danp2/au3WebDriver/issues/354#issuecomment-1201402121
> Ultimately I am thinking to be possible of something like this:
> 
> ```autoit
> _WD_FrameEnter($sSession, "Null/2/0/0")
> ```
this PR is finall implementation to this concept
not related

_WD_FrameEnter($sSession, 'null/2/0') - path support

---

wd_capabilities.au3

Documentation from here:
https://sites.google.com/a/chromium.org/chromedriver/capabilities
says:
<html>
<body>
mobileEmulation | dictionary |   | A dictionary with either a value for “deviceName,” or values for “deviceMetrics” and “userAgent.” Refer to Mobile Emulation for more information.
-- | -- | -- | --
</body>
</html>
As I'm not English native speaker I was not aware that saying `values for “deviceMetrics” ` they had in the meaning that `deviceMetrics` is nested dictionary/object.
You can notice that on this page: 
https://sites.google.com/a/chromium.org/chromedriver/capabilities
that:
1. There is quite good documentation for: `perfLoggingPrefs object` 
2. Not so good documentation for: `mobileEmulation object`
3. And IMHO lack of documentation for: `deviceMetrics object`
For this …

Capability: deviceMetrics + Nested dictionary

---

wd_core.au3

__WD_Get/Put/Delete should detect a prior error condition and not overwrite the value with a different error code
`__WD_Get("ftp://localhost:4444")` generates the following error, which is technically incorrect because the HTTP request never actually occurred -- 
`__WD_Get ==> Send / Recv error [6] : HTTP status = 0`
The correct error condition is reported --
`__WD_Get ==> Invalid value [4] : HTTP status = 0`
- OS Arch.: …

Improve error detection in winhttp wrapper functions

---

wd_helper.au3

removed `options[i].selected` as this was irrational that we return a value that will always be equal `true`
added new column `group name` to the result
refactoring JS for better code maintaince.
`options[i].selected` always be equal `true` as we use `var options = SelectElement.selectedOptions;`
refactored JS for better code maintaince.
`options[i].selected` replaced with `o.parentNode.label`
none
not related

_WD_ElementSelectAction 'selectedOptions' group

---

wd_helper.au3

added new column `group name`  to the result, and refactoring JS for better code maintaince.
Difficult to move to brwoser console and check.
No information about `group name` 
JavaScript code was refactored to use functions because this is easier to copy them to browser and test and maintain in the future.
New column `group name` gives better information where `<option>` is placed in `HTML DOM` structure.
none
not related

_WD_ElementSelectAction 'options' added group name

---

wd_helper.au3

Functions should have more validation / error checking.
In case when there is no need to select options because they are already selected there should not be done any change to `HTML DOM` so also event should not be fired.
JS code just going on without any validation
1.
check if `SelectElement` has `multiple` atribute and set error to `$_WD_ERROR_ElementIssue` if there element is not `multiple` able.
2.
return false when no selection was taken, and not fires change event in such case.
https://github.com/Danp2/au3WebDriver/issues/368#issuecomment-1209081023
not related

_WD_ElementSelectAction 'selectAll' JS validation

---

wd_demo.au3
wd_helper.au3

This PR add feature to easily select single `<option>` element by its label
no way for easy way to select single option by LabelName
1.
can be easily done with
```autoit
_WD_ElementSelectAction($sSesion, $sSelectElement, 'singleLabel', 'LabelNameToSeclect')
```
2.
Additionally `_WD_ExecuteScript` currently returns true or false as JavaScript was refactored
3.
JavaScript code was refactored to use `functions` because this is easier to copy them to browser and test and maintain in the future.
4.
JavaScript code is stored as static …

_WD_ElementSelectAction + SINGLESELECT

---

wd_helper.au3

if you use
```autoit
_WD_ElementSelectAction($sSession, $sSelectElement, 'SINGLESELECT', 'ParroT')
```
instead
```autoit
_WD_ElementSelectAction($sSession, $sSelectElement, 'SINGLESELECT', 'Parrot')
```
Then you will get error= `$_WD_ERROR_ElementIssue` but the return from JS is not empty string but false.
correct error number = `$_WD_ERROR_NoMatch`
https://github.com/Danp2/au3WebDriver/pull/377#issuecomment-1217902621
not related

Fix coding where $vResult is compared with an empty string

---

wd_core.au3

unification description for `$sSelector` parameter
`_WD_ElementOptionSelect`, `_WD_GetShadowRoot`, `_WD_SelectFiles` and finally `_WD_WaitElement` all this function have far way better description for `$sSelector` than `_WD_FindElement`
unified common `$sSelector` parameter description
none
not related

_WD_FindElement $sSelector header unification

---

wd_helper.au3

IsKeyword Return should be changed: variable > const
was discussed here: https://github.com/Danp2/au3WebDriver/issues/365
was discussed here: https://github.com/Danp2/au3WebDriver/issues/365
https://github.com/Danp2/au3WebDriver/issues/365
not related

wd_helper IsKeyword checks declared as const

---

README.md
wd_demo.au3
wd_helper.au3

was discussed here:
https://github.com/Danp2/au3WebDriver/issues/354
no way to list frames list
it is easy with `_WD_FrameList`
https://github.com/Danp2/au3WebDriver/issues/354#issuecomment-1203042673
can be tested with:
```autoit
Func UserTesting() ; here you can replace the code to test your stuff before you ask on the forum
_WD_Navigate($sSession, 'https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe')
_WD_LoadWait($sSession)
; Example 1 - from 'https://www.w3schools.com' get frame list as string
ConsoleWrite(_WD_FrameList($sSession,  False) & @CRLF)
; Example 2 - from 'https://www.w3schools.com' get frame list as array, with HTML content of each document
Local $aFrameList = _WD_FrameList($sSession,  True, '', True)
_ArrayDisplay($aFrameList, 'Example 2', 0, 0, Default, …
```

_WD_FrameList

---

wd_helper.au3

`_WD_LoadWait` should have better error handling and logging
On `$_WD_DEBUG_Error` function do not set complete [information about `$iTimeout` reason](https://www.w3schools.com/jsref/prop_doc_readystate.asp).
`_WD_ExecuteScript($sSession, 'return document.readyState', '', Default, $_WD_JSON_Value)` can set error to <> `$_WD_ERROR_Timeout` what was not documented in header.
added support for `$_WD_ERROR_Exception`
https://www.w3schools.com/jsref/prop_doc_readystate.asp
and `$iExt` shows latest status from: https://www.w3schools.com/jsref/prop_doc_readystate.asp
I was working with https://github.com/Danp2/au3WebDriver/pull/362 and because of this https://github.com/Danp2/au3WebDriver/pull/362#issuecomment-1225545526 I was thinking …

_WD_LoadWait - better error handling and logging

---

wd_demo.au3

fixing empty `Screen2.png` on FF in `DemoWindows` 
`DemosFunction` from `wd_demo.au3` are not properly waiting for the page to finish loading.
For example using FF i get empty `Screen2.png` with `DemoWindows`
after adding `_WD_LoadWait` to `_Demo_NavigateCheckBanner` it is fixed
I was testing: [DemoWindows in wd_demo: review all "Demo****" function](https://github.com/Danp2/au3WebDriver/issues/254)
I notice that using FF i get empty `Screen2.png`
FF

_Demo_NavigateCheckBanner added _WD_LoadWait

---

wd_demo.au3
wd_helper.au3

I think we should provide new feature for _WD_LoadWait() as there can be cases that you would like to wait not for complete but for interactive or even loaded will be enough to continue processing like there was no error.
`_WD_LoadWait` always wait for ReadyState = complete
you can set `$iState` to check for desired state as described here: https://www.w3schools.com/jsref/prop_doc_readystate.asp
```
uninitialized - Has not started loading
loading - Is loading
loaded - Has been loaded
interactive - Has loaded enough to interact with
complete - Fully loaded
```
this was discussed here:   [_WD_LoadWait() enhancements](https://github.com/Danp2/au3WebDriver/issues/385)
not related

_WD_LoadWait added DesiredReadyState checking

---

wd_helper.au3

Enhance the existing _WD_LinkClickByText function by optionally allowing the specification of a starting element.
Entire webpage is searched
Uses optional Starting Element parameter of _WD_FindElement to allow the search to be limited to a specific section of the webpage

_WD_LinkClickByText: Add starting element

---

wd_core.au3

Use revised capabilities when one isn't provided.
Current default is `{}`, which produces an error with most web drivers.
New default is `{"capabilities":{}}`

_WD_CreateSession: Revise default capabilities

---

wd_helper.au3

_WD_ElementActionEx: will scroll the target element into view by default
Webdriver Exception due to element not being visible in the view port
Forcibly scroll the element into view before performing further actions.
Fixes #403 

_WD_ElementActionEx: Scroll element into view by default

---

wd_helper.au3

fixing error reporting
return point always return success
```autoit
Return SetError(__WD_Error($sFuncName, $_WD_ERROR_Success), 0, $sValue)
```
returns proper $iErr
```autoit
Return SetError(__WD_Error($sFuncName, $iErr), 0, $sValue)
```
none
not related

_WD_FrameLeave error reporting fix

---

wd_helper.au3

Sleep() should not be used directly to have the $_WD_ERROR_UserAbort feature available
after scrolling script is stopped by Sleep() function whith out possibility to interact with.
__WD_Sleep() gives more interaction to the script
I would like to do this more flexible the script should check if it is visible or not and then scroll or not, after which should wait to be visible, and not only simply Sleep()
not related

_WD_ElementActionEx - inner comments suplemented

---

wd_core.au3

_WD_Window($sSession, "handles") returns an array of handles. This lets _WD_Window accept its own return values directly instead of having to remember to type '{"handle":"' & $aHandles[1] & '"}' each time
_WD_Window needs formatted handles
_WD_Window attempts to format unformatted handles
N/A
- OS: Windows 10
- OS Arch.: X64
- Browser: Edge
- Browser version: 110.0.1587.50

Let _WD_Window accept unformatted handles

---

wd_core.au3

Add detection for failure to locate a shadow root
Generic `$_WD_ERROR_Exception` is returned when the shadow root can't be located
`$_WD_ERROR_NoMatch` is returned

__WD_DetectError: shadow root not found detection

---

wd_core.au3

Pause before shutting down webdriver consoles to allow them to finish any background processing
See #440 
_WD_Shutdown will default to pausing for 2 seconds before killing the target webdriver. The length can be overridden using the new optional `$iDelay` parameter.
Code is commented regarding the intentional lack of checking for errors following the call to __WD_Sleep

_WD_Shutdown: Add delay before closing webdriver

---

wd_core.au3

Remove leftover checks for `$_WD_HTTPRESULT = $HTTP_STATUS_OK` 
Errant checks for `$_WD_HTTPRESULT = $HTTP_STATUS_OK`, which were previously used before `__WD_DetectError` was added
Remove leftover code

Remove leftover $_WD_HTTPRESULT checks

---

CHANGELOG.md
README.md
wd_helper.au3

Add function to enable retrieval of current browsing context<br>
No simple way to determine current browsing context
`_WD_GetContext` can be used to obtain the current browsing context.
Eliminates need to call `_WD_FrameList`, which requires many calls to webdriver
N/A

Add _WD_GetContext

---

wd_demo.au3

Better error handling in WD_Demo.
Not stopts processing even after error
should stop in case of error
I was working on:
https://github.com/Danp2/au3WebDriver/pull/454
and notice the issue that after unsuccessfull navigating it still doing some other struff
not related

wd_demo.au3 - better error handling

---

CHANGELOG.md
wd_demo.au3
wd_helper.au3

this change give user possibility to provide they own `$iDelay` and `$iTimeout` to have ability to wait for web page will be entirely loaded including all frames.
no way to use custom `$iDelay` and `$iTimeout` settings in `_WD_FrameList()` calls
and now you can do this easily
https://github.com/Danp2/au3WebDriver/issues/420
not related

Expand _WD_FrameList with Delay and Timeout parameters

---

CHANGELOG.md
wd_core.au3
wd_helper.au3

Implement fixes / improvement to _WD_GetFreePort
- No distinction between error conditions
- Wrong parameters passed to __WD_Error
- Return separate error code if __WinAPI_GetTcpTable fails
- Return starting port number ($iMinPort) instead of 0 when an error is detected
- Add $sMessage logging
- Fix issue with __WD_Error parameters

_WD_GetFreePort fixes/improvements

---

wd_demo.au3

cleanup adjustment for Au3Check 
unsed variables are poped up by Au3Check
all is fine
none
not related

wd_demo.au3 - UserFile() cleaned up

---

wd_demo.au3

user using `UserTesting()` with `UserTesting.au3` should have ability to set values for variables, this is limited as `Execute()` have their specific usage, and given this particular need, one could even say that it is a limitation, which can be tested with this following snippet which shows that `$b` is not set to 1 as `Execute()` evaluates expression and return results from this evalutation.
```autoit
Local $a = 1
Local $v = Execute("$a+1") ; $v is set to 2
ConsoleWrite("$v=" & $v & @CRLF)
Local $b
Execute("$b=1")
ConsoleWrite("$b=" & $b & @CRLF)
Local $c
ConsoleWrite(Execute("$c=1") & @CRLF)
```
description in: https://github.com/Danp2/au3WebDriver/issues/461
It is possible to use such `UserTesting.au3`:
```autoit
__UserAssign(0, 'Absolute Identifiers > _WD_FrameEnter|Relative …
```

wd_demo.au3 : $_VAR support in UserFile()

---

wd_helper.au3

If `$bReturnAsArray=True`  then even if third `__WD_FrameList_Internal` iteration will fire error then it returs string which should be converted to array
if some `__WD_FrameList_Internal` iteration will fire error then string will be returned even if `$bReturnAsArray=True`  was requested
Proper Array
I hit this error when testing:
https://github.com/Danp2/au3WebDriver/pull/462
not related

_WD_FrameList - $bReturnAsArray fix

---

usertesting.au3
wd_demo.au3

As I mention before: https://github.com/Danp2/au3WebDriver/pull/462#issuecomment-1522290146
`UserFile()` process `UserTesting.au3` only once and after processing close browser
You can choose new or the same `UserTesting.au3` and process them again without closing browser.
Was tested with `usertesting.au3` modified with this PR, and with separate `usertesting_WD_GetContext.au3` which contains:
```autoit
ConsoleWrite("! START" & @CRLF)
__SetVAR(0, "Absolute Identifiers > _WD_FrameEnter|Relative Identifiers > _WD_FrameEnter|IFRAME/FRAME attributes|URL|Body ElementID|IsHidden|MatchedElements")
ConsoleWrite("! 0 - $_VAR[0] = " & $_VAR[0] & @CRLF)
_Demo_NavigateCheckBanner($sSession, "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe", '//*[@id="snigel-cmp-framework" and …
```

wd_demo.au3 - ability to repeat "UserFile" processing

---

wd_helper.au3

Log and specicially `$sParameters` should maske `Value` due to LAW issues (like GDRP), It was already suplemented in `_WD_ElementAction`
Log can contain restrictive data like personal data or passwords
'<masked>'
None
not related

_WD_SetElementValue - masking value in $sParameters

---

wd_helper.au3

Closes #466 
When using $_WD_OPTION_Advanced in _WD_SetElementValue, $sValue is not escaped
Behavior is unchanged. Added remark to document that the user is responsible for formatting the data prior to calling _WD_SetElementValue in Advanced mode.

_WD_SetElementValue - Add remark

---

wd_helper.au3

Fixes #470 
#469 changed the way strings are encoded within _WD_ExecuteScript, which results in extra string escaping in _WD_GetElementByRegEx
- Removed line in _WD_GetElementByRegEx causing extra backslash escaping
- Added details to remarks of _WD_Storage

Follow up to  #469

---

CHANGELOG.md
wd_helper.au3

Removes invalid check for _WinAPI_GUIDFromString; fixes #474 
_WD_FrameEnter incorrectly returns invalid argument when using Chrome or MSEdge
Eliminate GUID check and special processing for $_WD_ERROR_InvalidArgue
- Chrome and MSEdge

Fix error in _WD_FrameEnter

---

CHANGELOG.md
wd_helper.au3

- Properly handle when script execution returns Null value
- Correct identification of frames
- Incorrect string comparison
- Error improperly detected when `document.elementFromPoint` returns `Null`
- Return empty string when  `document.elementFromPoint` returns `Null` without setting @error
- Correctly identify frame/iframe elements

Fix _WD_GetElementFromPoint

---

CHANGELOG.md
wd_helper.au3

Adjust xpaths used in _WD_GetTable so that headers are correctly included in the generated array.
- Function fails if first row contains header elements (TH) instead of data elements (TD)
- Rows containing header data are missing from the array
Xpath conditions have been modified to fix the above two improper behaviors

_WD_GetTable: Adjust xpaths to work with headers

---

CHANGELOG.md
wd_core.au3

Fixes #487 
Stripping of tabs and spaces from JS can result in code that no longer functions properly.
Code is processed as-is. Any reformatting that is required should be performed prior to calling _WD_ExecuteScript

_WD_ExecuteScript: don't reformat JS code

---

CHANGELOG.md
wd_helper.au3

Return additional error code to indicate invalid parameters.
Empty string is returned, but no error code is generated
Sets @err to $_WD_ERROR_InvalidArgue if a negative coordinate is detected

_WD_GetElementFromPoint: Detect invalid coordinates

---

wd_helper.au3

This is fix for Au3Check `warning: .......: declared, but not used in func.`
Au3Check throws errors like `warning: $aElements: declared, but not used in func.`
no errors
none
not related

Au3Check + _WD_GetTable

---

wd_helper.au3

Even internall function in UDF should have UDF prefix to make them more unique to not colide with any possible user private function, or other UDF
__Make2Array() is to common
__WD_Make2Array() name is corelated to this UDF
SciTE calltips shows the function name and you at first glance know where it belongs
not related

__Make2Array rename  __WD_Make2Array

---

wd_helper.au3

There is a need to locate `<table>` element in a common way.
For this reason `_WD_GetTable()` should have the same possibility as others like  `_WD_FindElement()` , `_WD_WaitElement()` and others.
`_WD_GetTable()` only support $_WD_LOCATOR_ByXPath
```autoit
_WD_GetTable($sSession, "//table")
```
`_WD_GetTable()` support all $_WD_LOCATOR_***
```autoit
_WD_GetTable($sSession, $_WD_LOCATOR_ByXPath, "//table")
```
`!!! SCRIPT BREAKING CHANGE !!!`
All `_WD_GetTable()` usage requires to add new 2nd parameter $_WD_LOCATOR_ByXPath, and moving previously/recently the second parameter to the third position
https://github.com/Danp2/au3WebDriver/issues/497
not related

_WD_GetTable() - support for $sStrategy

---

wd_capabilities.au3
wd_helper.au3

proper $JSON_* names should be used
$iErr should be used in all places in the same way
unrelated to the intent of this PR
not changed
none
none
not related

Fixing names and $iErr usage

---

wd_helper.au3

`$_WD_ERROR_InvalidValue` in `_WD_GetBrowserPath` header 
but `_WD_GetBrowserPath` is not setting `$_WD_ERROR_InvalidValue`
`$_WD_ERROR_InvalidValue` removed from `_WD_GetBrowserPath` header
none
none
not related

_WD_GetBrowserPath and $_WD_ERROR_InvalidValue

---

wd_demo.au3

Port should be direct defined in DriverParams
chomium based browser not starting
now its starts properly
none
https://www.autoitscript.com/forum/topic/212201-chromedriver-issues-august-2024
https://chromium.googlesource.com/chromium/src/+/6f33d75f071e322c4a3e49b0a4ac2022e5b6cada
MSEdge, Chrome

Update wd_demo.au3 - DriverParams direct port definition

---

wd_helper.au3

Use JS trim function to remove whitespace from textContent results
Array can contain test characters such as \n and \t
All leading and trailing whitespace characters are removed from cell contents
Describe how the changes will affect other functions, potential script breaking changes, etc.
https://www.autoitscript.com/forum/topic/212230-whitespace-characters-showing-when-accessing-a-table-using-_wd_gettable
- Browser …

_WD_GetTable: Trim whitespace

---

wd_helper.au3

User should be able to provide specific/desired browser version to download/update desired driver
computer station should be connected to internet to be able to get driver related to current computer station
you can check browser version computer only with INTRANET (not connected to internet) store them for example to INI file, 
and downlad the desired driver on different computer
none
https://www.autoitscript.com/forum/topic/210991-webdriver-_wd_updatedriverfirefox-dont-work-on-intranet
https://www.autoitscript.com/forum/topic/210991-webdriver-_wd_updatedriverfirefox-dont-work-on-intranet/?do=findComment&comment=1525803
not related

_WD_UpdateDriver - desired BrowserVersion

---

wd_helper.au3

Don't encode the backslash character when unicode character is used with _WD_JsonActionKey
Unicode characters are encoded so that they begin with a double backslash
Check for unicode character and prevent double backslash
https://www.autoitscript.com/forum/topic/212262-webdriver-udf-_wd_elementactionex-reports-errors-when-trying-to-use-command-modifierclick/
Signed-off-by: Dan Pollak …

_WD_JsonActionKey: Don't encode Unicode characters

---

wd_helper.au3

__WD_ErrHnd should do some notification to __WD_Error
no information about COM Error reasons.
__WD_ErrHnd added notification to __WD_Error
none
https://github.com/Danp2/au3WebDriver/pull/512
not related

__WD_ErrHnd added notification to __WD_Error

---

CHANGELOG.md
wd_helper.au3

Enforce usage of $INET_FORCERELOAD with InetRead
InetRead defaults to retrieving the file from the local cache
Forces a reload from the remote site
Affects _WD_IsLatestRelease & __WD_GetLatestWebdriverInfo
Fixes #527 
Signed-off-by: Dan Pollak <danpollak2@gmail.com>

Fix: Ensure InetRead usage isn't using local cache

---

wd_capabilities.au3

When adding capability where value are Booleans they should be changed to lower string
using:
```autoit
_WD_CapabilitiesDefine($_WD_KEYS__SPECIFICVENDOR_PRIMITIVE, 'useAutomationExtension')
_WD_CapabilitiesAdd('useAutomationExtension', False)
_WD_CapabilitiesDump(@ScriptLineNumber)
```
will delete previously added capabilities
works fine
none
https://github.com/Danp2/au3WebDriver/issues/531#issuecomment-3078574958
testing script:
https://github.com/Danp2/au3WebDriver/issues/531#issuecomment-3078580703
This issue can be deeply …

_WD_CapabilitiesAdd - IsBool($value1) - IsBool($value2)
